export * from './home'
export * from './notFound'
export * from './signIn'
export * from './register'
export * from './detail'
export * from './search'
export * from './shoppingCart'
export * from './placeOrder'
export * from '../test/marginCollapsing'
export * from '../test/holyGrailLayout'

